version: '2'
services:
  django:
    image: ejplatform/ej-server:master
    environment:
      DJANGO_DB_URL: psql://ejdb:ejdb123ej4@postgres:5432/ejdb
      DJANGO_DEFAULT_FROM_EMAIL: ej <noreply@ejplatform.org>
      RABBIT_ENV_RABBITMQ_PASS: ejrabbit
      COURIER_ONESIGNAL_APP_ID: OTRkNTc1OTMtNjU5Zi00ZTUyLTgwNmMtMTI1ZDYwZDZlODc5
      DJANGO_ACCOUNT_ALLOW_REGISTRATION: 'True'
      MAILGUN_SENDER_DOMAIN: ''
      DJANGO_ALLOWED_HOSTS: icd.ejplatform.org,www.icd.ejplatform.org
      REDIS_URL: redis://redis:6379
      DJANGO_ADMIN_URL: admin/
      COURIER_DEFAULT_PROVIDER: onesignal
      DJANGO_SETTINGS_MODULE: ej.settings
      DJANGO_RECAPTCHA_PUBLIC_KEY: 6LcQnE0UAAAAAH24gtlKpyXlHGrKqhbJ513z64Tq
      DEBUG: 'true'
      COURIER_ONESIGNAL_USER_ID: 4151b78e-ab22-43e6-910f-4574d234b60a
      DJANGO_MAILGUN_API_KEY: key-02f9b61e5f407916329bdb9a8b6030e9
      DJANGO_RECAPTCHA_PRIVATE_KEY: 6LcQnE0UAAAAAKx6l0eS4ur6M3BwMKh66PkOKjJN
      RABBIT_ENV_USER: ejrabbit
      DJANGO_SECRET_KEY: pqowieu12341rQ1W345E31RD5alsdk123456786543safdhas34231
    volumes:
      - ./ej/statics:/app/staticfiles/media
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis

  backend:
    image: ejplatform/ej-nginx:master
    volumes:
      - ./ej/statics/:/usr/share/nginx/html/media
    ports:
      - 8080:80/tcp
    links:
      - django
    depends_on:
      - django

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: ejdb
      POSTGRES_PASSWORD: ejdb123ej4
      POSTGRES_USER: ejdb
    volumes:
      - ./ej/postgres:/var/lib/postgresql/data

  redis:
    image: redis:3
