default:
  server_name: luanguimaraes.me
  service_port: 80

guardianes_api:
  server_name: guardianes.luanguimaraes.me
  service_port: 80

guardianes_dashboard:
  server_name: guardianesdata.luanguimaraes.me
  service_port: 8080
